/** Generated by scripts/check-critical-path.mjs. Do not edit by hand. */
var Cxp14CriticalPathStamp = (function () {
  'use strict';
  return Object.freeze({
    contractVersion: 1,
    hashes: Object.freeze({
      "src/ingestion/Cxp13Runtime.js": "829a9b2e4cd8f03f6b45636d547474d5e081601b6a5ea5f7f5ecdaaec9a31fa6",
      "src/ingestion/IngestionPipelineController.js": "f795a58a58fd355d7df732175f21ec95a4baad5bdd0517edee55b76ebbd48d96",
      "src/ingestion/InputAdapter.js": "f7b023024b92b9bf077f65555d0fcdb7369d8b25c1d9b9243d47b65411cee830",
      "src/repository/RawDataRepository.js": "d2d41fedcae3d00cc2c8762d6d13e2c5c1d49f18db7ac85bf9fc5df9553a5a4b",
      "src/repository/StagingRepository.js": "ecf25e76662630f23b0ffa12314f7dddc830f674370778c737cf91b81dab1047",
      "src/services/CommitService.js": "ed0ccc6de4c5d0349b43a8802f81532e5d5a8eb93e01b56cb45d7c83a8f41d16",
      "src/services/RollbackService.js": "93e95aaa2914792c4759e82e41dfbdd61ccc3ba1d66e16cf87dfc09be1d7cd98"
    }),
    pass: true,
    version: 1,
  });
})();

if (typeof module !== 'undefined' && module.exports) module.exports = Cxp14CriticalPathStamp;
