/** Generated by scripts/check-critical-path.mjs. Do not edit by hand. */
var Cxp14CriticalPathStamp = (function () {
  'use strict';
  return Object.freeze({
    contractVersion: 1,
    hashes: Object.freeze({
      "src/ingestion/Cxp13Runtime.js": "18d65b41ecba847637bca0068fa964364290f6c52b993dad048b790e4d0a38c7",
      "src/ingestion/IngestionPipelineController.js": "6ca27bf1fc320c99e74077ee63dd26e7c7ec8dcfc29b934f4ef517274a6d2e08",
      "src/ingestion/InputAdapter.js": "24a3282a2ca5c31f4e0e3cab694b0411e2843d427378eceaa7cb35c606c0fefa",
      "src/repository/RawDataRepository.js": "668eac765e984da932062f5abb257ea6c646a7ae8c46aa4b1b4988d7caf85818",
      "src/repository/StagingRepository.js": "83b090ecbf62adb66159778a6e3ee1b598f025c0d88b3452548c07809960db0b",
      "src/services/CommitService.js": "a35913e72f3c5a1409dbdbd21d9291ffed89da418b2b607ffefae694d3e3fbb4",
      "src/services/RollbackService.js": "a828b33ff26cb21bf120822f0adb1dab9186010926d234b16c98e0fb113e5229"
    }),
    pass: true,
    version: 1,
  });
})();

if (typeof module !== 'undefined' && module.exports) module.exports = Cxp14CriticalPathStamp;
